sudo: required
language: c
services:
- docker
compiler:
- gcc
- clang
env:
  matrix:
    - PYTHON_INTERPRETER=python2
    - PYTHON_INTERPRETER=python3
  global:
    - CODECOV_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
script:
  - ./.ci/travis.run
after_failure:
  - cat build/test-suite.log
after_success:
  - |
    if [ "$CC" == "gcc" ] && [ "$PYTHON_INTERPRETER" == "python3" ]; then
        bash <(curl -s https://codecov.io/bash)
    fi